import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: 'home',
    title: 'Home',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'user',
    title: 'Users',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'person',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'hotel',
    title: 'Hotels',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'location_city',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'event',
    title: 'Events',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'event_note',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'service',
    title: 'Services',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'room_service',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'typeRoom',
    title: 'Type Rooms',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'king_bed',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'room',
    title: 'Rooms',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'local_hotel',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
];
